name: CI
on:
  pull_request:
    paths-ignore:
    - docs/**
    - '**/*.md'
    - LICENSE
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      non_docs_changed: ${{ steps.changed.outputs.any_changed }}

    steps:
    - name: Checkout Source
      uses: actions/checkout@v5

    - name: Detect non-doc changes in last PR push
      id: changed
      uses: tj-actions/changed-files@v47
      with:
        since_last_remote_commit: true
        files_ignore: |
          docs/**
          **/*.md
          LICENSE

  tests:
    needs: changes
    if: ${{ github.event_name != 'pull_request' || needs.changes.outputs.non_docs_changed == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        python-version:
        - '3.10'
        - '3.14'

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
    - name: Checkout Source
      uses: actions/checkout@v5
    - name: Setup uv
      uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build
      run: uv sync --no-editable --group test
    # -------------------
    # Ruff lint + format
    # -------------------
    - name: Run Ruff lint
      run: uv run ruff check src/ --output-format=github
    - name: Check Ruff formatting
      run: uv run ruff format --check src/

    # -------------------
    # Run test suite
    # -------------------
    - name: Run tests with coverage
      run: uv run --no-sync pytest --color=yes

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_SECRET }}
        files: coverage.xml
        flags: unittests
        fail_ci_if_error: false
        verbose: true

  type-check:
    needs: changes
    if: ${{ github.event_name != 'pull_request' || needs.changes.outputs.non_docs_changed == 'true' }}
    runs-on: ubuntu-latest
    name: type check

    concurrency:
      group: ${{ github.ref }}-dev
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 0

    - name: Setup uv
      uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
      with:
        # Match minimal supported Python version
        # to make sure we're not using unparseable syntax
        python-version: '3.10'

    - name: Run mypy
      run: uv run --group typecheck mypy src
